### ISSUE TITLE
avoid highlight.js build error

### ISSUE THREAD

**Issue by hufengtao** [sanmoskalenko/hsapp#1]
add

:js-options {:resolve {"highlight.js" {:target :npm :require "highlight.js/lib/core"}
                                  "lowlight" {:target :npm :require "lowlight/lib/core"}}}

to 

 :builds       {:app {:target     :browser
                      :output-dir "resources/public/js/compiled/js"
                      :js-options {:resolve {"highlight.js" {:target :npm :require "highlight.js/lib/core"}
                                  "lowlight" {:target :npm :require "lowlight/lib/core"}}}
                      :asset-path "/js/compiled"
                      :modules    {:app {:init-fn ui.health.core/init}}
                      :devtools   {:preloads [devtools.preload
                                              day8.re-frame-10x.preload]}
                      :dev        {:compiler-options {:closure-defines
                                                      {re-frame.trace.trace-enabled?        true
                                                       day8.re-frame.tracing.trace-enabled? true}}}
                      :release    {:build-options
                                   {:ns-aliases {day8.re-frame.tracing
                                                 day8.re-frame.tracing-stubs}}}}}

**Comment by sanmoskalenko** [comment]
corrected, thank you very much!
